import type { EnvironmentProfile } from './ambiencePresets';

// Bundled, same-origin ambient "bed" textures — no external network calls,
// no API keys, no CORS, no rate limits. Generated by
// scripts/generate-ambience-beds.mjs (re-run it to regenerate/tweak).
const BED_ASSET_BY_PROFILE: Record<EnvironmentProfile, string> = {
  CAFE: '/ambience/cafe.wav',
  CITY: '/ambience/city.wav',
  OFFICE: '/ambience/office.wav',
  NATURE: '/ambience/nature.wav',
  ROOM: '/ambience/room.wav',
};

export function bedAssetForProfile(profile: EnvironmentProfile): string {
  return BED_ASSET_BY_PROFILE[profile];
}

const bufferCache = new Map<string, Promise<AudioBuffer | null>>();

// Warm the HTTP cache while the lesson is still generating, so the bed is
// already on disk when the learner hits play. Only the bytes are prefetched:
// decoding needs an AudioContext, and that one is born on the first gesture
// inside AudioPlayer. Failures are irrelevant — the real load re-fetches.
export function prefetchAmbienceBed(profile: EnvironmentProfile): void {
  try {
    fetch(bedAssetForProfile(profile)).catch(() => undefined);
  } catch {
    /* no-op */
  }
}

// Fetch + decode a bundled bed asset into an AudioBuffer, cached by URL so
// repeated scene changes to the same profile don't redecode. Same-origin
// static asset, so this can never fail on CORS; only real I/O/decode errors
// are possible, and those degrade to `null` (caller falls back to
// synthetic-only ambience, matching today's behavior).
export function loadAmbienceBed(ctx: AudioContext, profile: EnvironmentProfile): Promise<AudioBuffer | null> {
  const url = bedAssetForProfile(profile);
  const cacheKey = `${url}`;
  let pending = bufferCache.get(cacheKey);
  if (!pending) {
    pending = fetch(url)
      .then(res => {
        if (!res.ok) throw new Error(`Ambience bed fetch failed: ${res.status}`);
        return res.arrayBuffer();
      })
      .then(arrayBuffer => ctx.decodeAudioData(arrayBuffer))
      .catch(err => {
        console.warn('[Ambience] Bed load failed, falling back to synthetic-only.', err);
        bufferCache.delete(cacheKey);
        return null;
      });
    bufferCache.set(cacheKey, pending);
  }
  return pending;
}
